apiVersion: v2
appVersion: 2.5.3
description: Rancher demo application, web UI showing scale of containers
name: rancher-demo
version: 2.8.0
icon: https://udemy-images.udemy.com/course/750x422/1527740_a494.jpg
type: application
